# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ffad87e2de0a1f8b50d2b8636c230d8a4c758d123c7efcd127eadf3bc40a401a5845d32797915f20d2145c80513a67fc683411b86c0faa95320c12892308402

test:
  secret_key_base: 5edd9fcdeecbfe34f4ad0a16f23316bb36775591438a4b1c0972b14eedb4aef1d94891243189133442177a65db8c4a36814cd9172b8bf4d981a18152425d6ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
